server:
  port: 8080

spring:
  application:
    name: dynamic-executor

thread:
  pool:
    core-pool-size: 2
    maximum-pool-size: 4
    keep-alive-time: 30
    time-unit: SECONDS
    queue-type: LINKED_BLOCKING
    queue-capacity: 50
    rejected-policy: CALLER_RUNS
